# Generated by Django 3.2.8 on 2021-10-08 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thefav', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
