# Generated by Django 3.2.8 on 2021-10-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thefav', '0005_auto_20211027_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='post_connected',
        ),
    ]
